//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Aplicación_de_Escritorio.SGC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InterfazRemotaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class InterfazRemota : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InicializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarPiezaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProponerPiezaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClientePorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDesguaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDesguacePorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroDesguaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPropuestasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InterfazRemota() {
            this.Url = global::Aplicación_de_Escritorio.Properties.Settings.Default.Aplicación_de_Escritorio_SGC_InterfazRemota;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InicializarCompletedEventHandler InicializarCompleted;
        
        /// <remarks/>
        public event SolicitarPiezaCompletedEventHandler SolicitarPiezaCompleted;
        
        /// <remarks/>
        public event ProponerPiezaCompletedEventHandler ProponerPiezaCompleted;
        
        /// <remarks/>
        public event ObtenerClienteCompletedEventHandler ObtenerClienteCompleted;
        
        /// <remarks/>
        public event ObtenerClientePorUsuarioCompletedEventHandler ObtenerClientePorUsuarioCompleted;
        
        /// <remarks/>
        public event ObtenerDesguaceCompletedEventHandler ObtenerDesguaceCompleted;
        
        /// <remarks/>
        public event ObtenerDesguacePorUsuarioCompletedEventHandler ObtenerDesguacePorUsuarioCompleted;
        
        /// <remarks/>
        public event RegistroClienteCompletedEventHandler RegistroClienteCompleted;
        
        /// <remarks/>
        public event RegistroDesguaceCompletedEventHandler RegistroDesguaceCompleted;
        
        /// <remarks/>
        public event ObtenerPropuestasCompletedEventHandler ObtenerPropuestasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Inicializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Inicializar() {
            this.Invoke("Inicializar", new object[0]);
        }
        
        /// <remarks/>
        public void InicializarAsync() {
            this.InicializarAsync(null);
        }
        
        /// <remarks/>
        public void InicializarAsync(object userState) {
            if ((this.InicializarOperationCompleted == null)) {
                this.InicializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInicializarOperationCompleted);
            }
            this.InvokeAsync("Inicializar", new object[0], this.InicializarOperationCompleted, userState);
        }
        
        private void OnInicializarOperationCompleted(object arg) {
            if ((this.InicializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InicializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitarPieza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SolicitarPieza(ENSolicitud solicitud) {
            object[] results = this.Invoke("SolicitarPieza", new object[] {
                        solicitud});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarPiezaAsync(ENSolicitud solicitud) {
            this.SolicitarPiezaAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void SolicitarPiezaAsync(ENSolicitud solicitud, object userState) {
            if ((this.SolicitarPiezaOperationCompleted == null)) {
                this.SolicitarPiezaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarPiezaOperationCompleted);
            }
            this.InvokeAsync("SolicitarPieza", new object[] {
                        solicitud}, this.SolicitarPiezaOperationCompleted, userState);
        }
        
        private void OnSolicitarPiezaOperationCompleted(object arg) {
            if ((this.SolicitarPiezaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarPiezaCompleted(this, new SolicitarPiezaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProponerPieza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProponerPieza(ENPropuesta propuesta) {
            object[] results = this.Invoke("ProponerPieza", new object[] {
                        propuesta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProponerPiezaAsync(ENPropuesta propuesta) {
            this.ProponerPiezaAsync(propuesta, null);
        }
        
        /// <remarks/>
        public void ProponerPiezaAsync(ENPropuesta propuesta, object userState) {
            if ((this.ProponerPiezaOperationCompleted == null)) {
                this.ProponerPiezaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProponerPiezaOperationCompleted);
            }
            this.InvokeAsync("ProponerPieza", new object[] {
                        propuesta}, this.ProponerPiezaOperationCompleted, userState);
        }
        
        private void OnProponerPiezaOperationCompleted(object arg) {
            if ((this.ProponerPiezaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProponerPiezaCompleted(this, new ProponerPiezaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENCliente ObtenerCliente(int id) {
            object[] results = this.Invoke("ObtenerCliente", new object[] {
                        id});
            return ((ENCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(int id) {
            this.ObtenerClienteAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(int id, object userState) {
            if ((this.ObtenerClienteOperationCompleted == null)) {
                this.ObtenerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerCliente", new object[] {
                        id}, this.ObtenerClienteOperationCompleted, userState);
        }
        
        private void OnObtenerClienteOperationCompleted(object arg) {
            if ((this.ObtenerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClienteCompleted(this, new ObtenerClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerClientePorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENCliente ObtenerClientePorUsuario(string usuario) {
            object[] results = this.Invoke("ObtenerClientePorUsuario", new object[] {
                        usuario});
            return ((ENCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClientePorUsuarioAsync(string usuario) {
            this.ObtenerClientePorUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ObtenerClientePorUsuarioAsync(string usuario, object userState) {
            if ((this.ObtenerClientePorUsuarioOperationCompleted == null)) {
                this.ObtenerClientePorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClientePorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerClientePorUsuario", new object[] {
                        usuario}, this.ObtenerClientePorUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerClientePorUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerClientePorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClientePorUsuarioCompleted(this, new ObtenerClientePorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDesguace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENDesguace ObtenerDesguace(int id) {
            object[] results = this.Invoke("ObtenerDesguace", new object[] {
                        id});
            return ((ENDesguace)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDesguaceAsync(int id) {
            this.ObtenerDesguaceAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerDesguaceAsync(int id, object userState) {
            if ((this.ObtenerDesguaceOperationCompleted == null)) {
                this.ObtenerDesguaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDesguaceOperationCompleted);
            }
            this.InvokeAsync("ObtenerDesguace", new object[] {
                        id}, this.ObtenerDesguaceOperationCompleted, userState);
        }
        
        private void OnObtenerDesguaceOperationCompleted(object arg) {
            if ((this.ObtenerDesguaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDesguaceCompleted(this, new ObtenerDesguaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDesguacePorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENDesguace ObtenerDesguacePorUsuario(string usuario) {
            object[] results = this.Invoke("ObtenerDesguacePorUsuario", new object[] {
                        usuario});
            return ((ENDesguace)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDesguacePorUsuarioAsync(string usuario) {
            this.ObtenerDesguacePorUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ObtenerDesguacePorUsuarioAsync(string usuario, object userState) {
            if ((this.ObtenerDesguacePorUsuarioOperationCompleted == null)) {
                this.ObtenerDesguacePorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDesguacePorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerDesguacePorUsuario", new object[] {
                        usuario}, this.ObtenerDesguacePorUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerDesguacePorUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerDesguacePorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDesguacePorUsuarioCompleted(this, new ObtenerDesguacePorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegistroCliente(ENCliente cliente) {
            object[] results = this.Invoke("RegistroCliente", new object[] {
                        cliente});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroClienteAsync(ENCliente cliente) {
            this.RegistroClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void RegistroClienteAsync(ENCliente cliente, object userState) {
            if ((this.RegistroClienteOperationCompleted == null)) {
                this.RegistroClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroClienteOperationCompleted);
            }
            this.InvokeAsync("RegistroCliente", new object[] {
                        cliente}, this.RegistroClienteOperationCompleted, userState);
        }
        
        private void OnRegistroClienteOperationCompleted(object arg) {
            if ((this.RegistroClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroClienteCompleted(this, new RegistroClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroDesguace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegistroDesguace(ENDesguace desguace) {
            object[] results = this.Invoke("RegistroDesguace", new object[] {
                        desguace});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroDesguaceAsync(ENDesguace desguace) {
            this.RegistroDesguaceAsync(desguace, null);
        }
        
        /// <remarks/>
        public void RegistroDesguaceAsync(ENDesguace desguace, object userState) {
            if ((this.RegistroDesguaceOperationCompleted == null)) {
                this.RegistroDesguaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroDesguaceOperationCompleted);
            }
            this.InvokeAsync("RegistroDesguace", new object[] {
                        desguace}, this.RegistroDesguaceOperationCompleted, userState);
        }
        
        private void OnRegistroDesguaceOperationCompleted(object arg) {
            if ((this.RegistroDesguaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroDesguaceCompleted(this, new RegistroDesguaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPropuestas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ObtenerPropuestas(ENSolicitud solicitud) {
            object[] results = this.Invoke("ObtenerPropuestas", new object[] {
                        solicitud});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPropuestasAsync(ENSolicitud solicitud) {
            this.ObtenerPropuestasAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void ObtenerPropuestasAsync(ENSolicitud solicitud, object userState) {
            if ((this.ObtenerPropuestasOperationCompleted == null)) {
                this.ObtenerPropuestasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPropuestasOperationCompleted);
            }
            this.InvokeAsync("ObtenerPropuestas", new object[] {
                        solicitud}, this.ObtenerPropuestasOperationCompleted, userState);
        }
        
        private void OnObtenerPropuestasOperationCompleted(object arg) {
            if ((this.ObtenerPropuestasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPropuestasCompleted(this, new ObtenerPropuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENSolicitud {
        
        private int idField;
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private bool negociadoAutomaticoField;
        
        private System.DateTime fechaRespuestaField;
        
        private System.DateTime fechaEntregaField;
        
        private ENEstadosPieza estadoField;
        
        private float precioMaxField;
        
        private int idClienteField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public bool NegociadoAutomatico {
            get {
                return this.negociadoAutomaticoField;
            }
            set {
                this.negociadoAutomaticoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
            }
        }
        
        /// <comentarios/>
        public ENEstadosPieza Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public float PrecioMax {
            get {
                return this.precioMaxField;
            }
            set {
                this.precioMaxField = value;
            }
        }
        
        /// <comentarios/>
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ENEstadosPieza {
        
        /// <comentarios/>
        USADA,
        
        /// <comentarios/>
        NUEVA,
        
        /// <comentarios/>
        NO_FUNCIONA,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENDesguace {
        
        private int idField;
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string nombreField;
        
        private string nifField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private string informacionAdicionalField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nif {
            get {
                return this.nifField;
            }
            set {
                this.nifField = value;
            }
        }
        
        /// <comentarios/>
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENCliente {
        
        private int idField;
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string nombreField;
        
        private string nifField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private string informacionAdicionalField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nif {
            get {
                return this.nifField;
            }
            set {
                this.nifField = value;
            }
        }
        
        /// <comentarios/>
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENPropuesta {
        
        private int idField;
        
        private string descripcionField;
        
        private System.DateTime fechaEntregaField;
        
        private ENEstadosPieza estadoField;
        
        private float precioField;
        
        private byte[] fotoField;
        
        private int idDesguaceField;
        
        private int idSolicitudField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
            }
        }
        
        /// <comentarios/>
        public ENEstadosPieza Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public float Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <comentarios/>
        public int IdDesguace {
            get {
                return this.idDesguaceField;
            }
            set {
                this.idDesguaceField = value;
            }
        }
        
        /// <comentarios/>
        public int IdSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                this.idSolicitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InicializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SolicitarPiezaCompletedEventHandler(object sender, SolicitarPiezaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarPiezaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarPiezaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProponerPiezaCompletedEventHandler(object sender, ProponerPiezaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProponerPiezaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProponerPiezaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerClienteCompletedEventHandler(object sender, ObtenerClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerClientePorUsuarioCompletedEventHandler(object sender, ObtenerClientePorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClientePorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClientePorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerDesguaceCompletedEventHandler(object sender, ObtenerDesguaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDesguaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDesguaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENDesguace Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENDesguace)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerDesguacePorUsuarioCompletedEventHandler(object sender, ObtenerDesguacePorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDesguacePorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDesguacePorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENDesguace Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENDesguace)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroClienteCompletedEventHandler(object sender, RegistroClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroDesguaceCompletedEventHandler(object sender, RegistroDesguaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroDesguaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroDesguaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPropuestasCompletedEventHandler(object sender, ObtenerPropuestasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPropuestasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPropuestasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591