/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormBase.java
 *
 * Created on 23-ene-2011, 12:30:48
 */

package aplicaciondesguace;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.swing.JPanel;
import org.apache.activemq.ActiveMQConnectionFactory;
import org.apache.activemq.command.ActiveMQTopic;

/**
 *
 * @author DAMIAN-MACBOOK
 */
public class FormBase extends javax.swing.JFrame {

    /** Creates new form FormBase */
    public FormBase(Desguace d,Empleado e) {

        initComponents();

        // al principio solo hay un panel, estos botones se encuentran deshabilidados
        btSiguiente.setEnabled(false);
        btAnterior.setEnabled(false);

        desguace=d;
        empleado=e;

        configuracion = new Configuracion();
        configuracion.leerConfiguracion("conf.xml");

        // creo el primer panel
        paneles = new ArrayList<JPanel>();
        numPaneles = 1;
        panelActual = 1;
        JPanel p = new PanelSolicitudes(this);
        paneles.add(p);

        panelPrincipal.add(p,"" + numPaneles);

        
        
    }

    public Desguace getDesguace(){

        return desguace;
    }

    public Empleado getEmpleado(){

        return empleado;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMenu = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btSiguiente = new javax.swing.JButton();
        btEditarUsuario = new javax.swing.JButton();
        btBuscarUsuario = new javax.swing.JButton();
        btNuevoUsuario = new javax.swing.JButton();
        btNuevoAdministrador = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        btChat = new javax.swing.JButton();
        btConectar = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        btSolicitudes = new javax.swing.JButton();
        btRecargar = new javax.swing.JButton();
        btRegistro = new javax.swing.JButton();
        btLimpiarRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criludage");
        setMinimumSize(new java.awt.Dimension(900, 750));

        btMenu.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\desplegable.png")); // NOI18N
        btMenu.setToolTipText("Menu");
        btMenu.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        btAnterior.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\anterior.png")); // NOI18N
        btAnterior.setToolTipText("Menu");
        btAnterior.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btSiguiente.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\siguiente.png")); // NOI18N
        btSiguiente.setToolTipText("Menu");
        btSiguiente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        btEditarUsuario.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\editaruser.png")); // NOI18N
        btEditarUsuario.setToolTipText("Menu");
        btEditarUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarUsuarioActionPerformed(evt);
            }
        });

        btBuscarUsuario.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\verempleados.png")); // NOI18N
        btBuscarUsuario.setToolTipText("Menu");
        btBuscarUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarUsuarioActionPerformed(evt);
            }
        });

        btNuevoUsuario.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\anadiruser.png")); // NOI18N
        btNuevoUsuario.setToolTipText("Menu");
        btNuevoUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoUsuarioActionPerformed(evt);
            }
        });

        btNuevoAdministrador.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\anadiradmin.png")); // NOI18N
        btNuevoAdministrador.setToolTipText("Menu");
        btNuevoAdministrador.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btNuevoAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoAdministradorActionPerformed(evt);
            }
        });

        btConfiguracion.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\options.png")); // NOI18N
        btConfiguracion.setToolTipText("Menu");
        btConfiguracion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });

        btChat.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\mostrarchat.png")); // NOI18N
        btChat.setToolTipText("Menu");
        btChat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChatActionPerformed(evt);
            }
        });

        btConectar.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\green_button.png")); // NOI18N
        btConectar.setToolTipText("Menu");
        btConectar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        btDesconectar.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\red_button.png")); // NOI18N
        btDesconectar.setToolTipText("Menu");
        btDesconectar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });

        btSolicitudes.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\document_32.png")); // NOI18N
        btSolicitudes.setToolTipText("Menu");
        btSolicitudes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolicitudesActionPerformed(evt);
            }
        });

        btRecargar.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\refresh.png")); // NOI18N
        btRecargar.setToolTipText("Menu");
        btRecargar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecargarActionPerformed(evt);
            }
        });

        btRegistro.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\clipboard.png")); // NOI18N
        btRegistro.setToolTipText("Menu");
        btRegistro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroActionPerformed(evt);
            }
        });

        btLimpiarRegistro.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DAMIAN-MACBOOK\\Mis documentos\\NetBeansProjects\\AplicacionDesguace\\images\\limpiar.png")); // NOI18N
        btLimpiarRegistro.setToolTipText("Menu");
        btLimpiarRegistro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btLimpiarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarRegistroActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Navegación");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solicitudes");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Preferencias");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ayuda en línea");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Registro");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNuevoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btChat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btLimpiarRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesconectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btChat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfiguracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNuevoAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNuevoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBuscarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSiguiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addComponent(btRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        panelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        
    }//GEN-LAST:event_btMenuActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        // si aun no estoy en el primer panel
        if(panelActual>1){
            // decremento el contador
            panelActual--;
            // paso al panel anterior
            ((CardLayout)panelPrincipal.getLayout()).previous(panelPrincipal);
            // se puede ir hacia delante
            btSiguiente.setEnabled(true);
        }
        // si estoy en el primer panel
        if(panelActual==1){
            // deshabilito el boton anterior
            btAnterior.setEnabled(false);
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        // si el panel no es el ultimo
        if(panelActual < numPaneles){
            // incremento el contador
            panelActual++;
            // paso al siguiente panel
            ((CardLayout)panelPrincipal.getLayout()).next(panelPrincipal);
            // se puede ir al panel anterior
            btAnterior.setEnabled(true);
        }
        // si estoy en el ultimo panel
        if(panelActual == numPaneles){
            // deshabilito el boton siguiente
            btSiguiente.setEnabled(false);
        }

    }//GEN-LAST:event_btSiguienteActionPerformed

    private void btEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarUsuarioActionPerformed
        
        addPanel(new PanelEditarEmpleado(this,empleado));
    }//GEN-LAST:event_btEditarUsuarioActionPerformed

    private void btBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarUsuarioActionPerformed
        
        addPanel(new PanelEmpleados(this,empleado));
    }//GEN-LAST:event_btBuscarUsuarioActionPerformed

    private void btNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoUsuarioActionPerformed

        addPanel(new PanelNuevoEmpleado());
    }//GEN-LAST:event_btNuevoUsuarioActionPerformed

    private void btNuevoAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoAdministradorActionPerformed
        
        addPanel(new PanelNuevoAdministrador());
    }//GEN-LAST:event_btNuevoAdministradorActionPerformed

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed

        addPanel(new PanelConfiguracion());
    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void btChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChatActionPerformed

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConectarActionPerformed

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolicitudesActionPerformed

        JPanel p = new PanelSolicitudes(this);
        paneles.add(p);
        addPanel(p);
        
    }//GEN-LAST:event_btSolicitudesActionPerformed

    private void btRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecargarActionPerformed

        for(int i = 0; i<paneles.size();i++){
            if(paneles.get(i)instanceof PanelSolicitudes){
                ((PanelSolicitudes)paneles.get(i)).Refrescar();
            }
        }

    }//GEN-LAST:event_btRecargarActionPerformed

    private void btRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroActionPerformed

         addPanel(new PanelRegistro());
    }//GEN-LAST:event_btRegistroActionPerformed

    private void btLimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimpiarRegistroActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBase(new Desguace(),new Empleado()).setVisible(true);
            }
        });
    }

    public void addPanel(JPanel p){

        numPaneles++;
        panelActual=numPaneles;
        panelPrincipal.add(p,""+numPaneles);
        ((CardLayout)panelPrincipal.getLayout()).show(panelPrincipal, ""+numPaneles);
        panelPrincipal.updateUI();
        btAnterior.setEnabled(true);
        btSiguiente.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btBuscarUsuario;
    private javax.swing.JButton btChat;
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btEditarUsuario;
    private javax.swing.JButton btLimpiarRegistro;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btNuevoAdministrador;
    private javax.swing.JButton btNuevoUsuario;
    private javax.swing.JButton btRecargar;
    private javax.swing.JButton btRegistro;
    private javax.swing.JButton btSiguiente;
    private javax.swing.JButton btSolicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    private int numPaneles = 0;
    private int panelActual = 0;
    private Configuracion configuracion;
    private ArrayList<JPanel> paneles = null;
    private Desguace desguace=null;
    private Empleado empleado=null;
}
