/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrimeraVezBienvenida.java
 *
 * Created on 23-ene-2011, 17:29:05
 */

package aplicaciondesguace;

/**
 *
 * @author DAMIAN-MACBOOK
 */
public class PanelPrimeraVezEmpleado extends javax.swing.JPanel {

    /** Creates new form PanelPrimeraVezBienvenida */
    public PanelPrimeraVezEmpleado() {
        initComponents();

    }

    public String getNombre(){
        return campoNombre.getText();
    }

    public String getPassword1(){
        return new String(campoPassword1.getPassword());
    }

    public String getPassword2(){
        return new String(campoPassword2.getPassword());
    }

    public boolean getAdministrador(){
        return checkAdmin.isSelected();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal2 = new javax.swing.JPanel();
        etiqTitulo = new javax.swing.JLabel();
        etiq1 = new javax.swing.JLabel();
        etiq2 = new javax.swing.JLabel();
        etiqNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiqPassword = new javax.swing.JLabel();
        checkAdmin = new javax.swing.JCheckBox();
        campoPassword1 = new javax.swing.JPasswordField();
        campoPassword2 = new javax.swing.JPasswordField();

        etiqTitulo.setFont(new java.awt.Font("Tahoma", 0, 14));
        etiqTitulo.setForeground(new java.awt.Color(0, 102, 204));
        etiqTitulo.setText("Introduciendo el primer empleado");

        etiq1.setText("Registro del primer empleado en la aplicación que tendrá privilegios de administrador.");

        etiq2.setText("Pulsa siguiente para continuar");

        etiqNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqNombre.setText("Nombre de Usuario");

        etiqPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqPassword.setText("Contraseña");

        checkAdmin.setSelected(true);
        checkAdmin.setText("Administrador");
        checkAdmin.setEnabled(false);
        checkAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipal2Layout = new javax.swing.GroupLayout(PanelPrincipal2);
        PanelPrincipal2.setLayout(PanelPrincipal2Layout);
        PanelPrincipal2Layout.setHorizontalGroup(
            PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etiq2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addComponent(etiqTitulo)
                        .addComponent(etiq1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPrincipal2Layout.createSequentialGroup()
                            .addComponent(etiqPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipal2Layout.createSequentialGroup()
                                    .addComponent(campoPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(checkAdmin)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPrincipal2Layout.createSequentialGroup()
                            .addComponent(etiqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        PanelPrincipal2Layout.setVerticalGroup(
            PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqTitulo)
                .addGap(18, 18, 18)
                .addComponent(etiq1)
                .addGap(41, 41, 41)
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqPassword)
                    .addComponent(campoPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(etiq2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAdminActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal2;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPasswordField campoPassword1;
    private javax.swing.JPasswordField campoPassword2;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JLabel etiq1;
    private javax.swing.JLabel etiq2;
    private javax.swing.JLabel etiqNombre;
    private javax.swing.JLabel etiqPassword;
    private javax.swing.JLabel etiqTitulo;
    // End of variables declaration//GEN-END:variables

}
