/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormBase.java
 *
 * Created on 23-ene-2011, 12:30:48
 */

package aplicaciondesguace;

import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DAMIAN-MACBOOK
 */
public class FormBase extends javax.swing.JFrame {

    /** Creates new form FormBase */
    public FormBase(Desguace d,Empleado e) {

        initComponents();

        // al principio solo hay un panel, estos botones se encuentran deshabilidados
        botonSiguiente.setEnabled(false);
        botonAnterior.setEnabled(false);

        // asigno el desguace y el empleado
        desguace=d;
        empleado=e;

        // anyado al log el inicio de sesion
        addLog("Iniciada la sesion: " + empleado.getUsuario());

        // cargo la configuracion
        configuracion = new Configuracion();
        configuracion.leerConfiguracion("conf.xml");

        // inicializo variables
        paneles = new ArrayList<JPanel>();
        numPaneles = 0;
        panelActual = 0;

        // creo el primer panel
        JPanel p = new PanelSolicitudes(this);
        addPanel(p);

        // si es administrador puedo crear empleados y administradores
        if(empleado.isAdministrador()){
            botonNuevoAdministrador.setEnabled(true);
            botonNuevoUsuario.setEnabled(true);
        }
        // si no, no puedo
        else{
            botonNuevoAdministrador.setEnabled(false);
            botonNuevoUsuario.setEnabled(false);
        }

        // al salir de la aplicacion pido confirmacion
        addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                        int opcion = JOptionPane.showConfirmDialog(null,
                                        "Realmente desea salir", "Confirmacion",
                                        JOptionPane.YES_NO_OPTION);
                        // si salgo, hago constancia de ello en el log
                        if (opcion == JOptionPane.YES_OPTION) {
                                addLog("Cerrada la sesion: " + empleado.getUsuario());
                                dispose();
                        }
                }
        });
    }

    public Desguace getDesguace(){

        return desguace;
    }

    public Empleado getEmpleado(){

        return empleado;
    }

    public Configuracion getConfiguracion(){

        return configuracion;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonSolicitudes = new javax.swing.JButton();
        botonRefrescar = new javax.swing.JButton();
        botonEditarUsuario = new javax.swing.JButton();
        botonVerUsuarios = new javax.swing.JButton();
        botonNuevoUsuario = new javax.swing.JButton();
        botonNuevoAdministrador = new javax.swing.JButton();
        botonConfiguracion = new javax.swing.JButton();
        botonChat = new javax.swing.JButton();
        botonConectar = new javax.swing.JButton();
        botonDesconectar = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        botonLimpiarRegistro = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criludage");
        setMinimumSize(new java.awt.Dimension(1000, 750));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Navegación");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solicitudes");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Preferencias");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ayuda en línea");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Registro");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/desplegable.png"))); // NOI18N

        botonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/anterior.png"))); // NOI18N
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/siguiente.png"))); // NOI18N
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/document_32.png"))); // NOI18N
        botonSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSolicitudesActionPerformed(evt);
            }
        });

        botonRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/refresh.png"))); // NOI18N
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });

        botonEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/editaruser.png"))); // NOI18N
        botonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarUsuarioActionPerformed(evt);
            }
        });

        botonVerUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/verempleados.png"))); // NOI18N
        botonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerUsuariosActionPerformed(evt);
            }
        });

        botonNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/anadiruser.png"))); // NOI18N
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        botonNuevoAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/anadiradmin.png"))); // NOI18N
        botonNuevoAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoAdministradorActionPerformed(evt);
            }
        });

        botonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/options.png"))); // NOI18N
        botonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionActionPerformed(evt);
            }
        });

        botonChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/mostrarchat.png"))); // NOI18N

        botonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/green_button.png"))); // NOI18N

        botonDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/red_button.png"))); // NOI18N

        botonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/clipboard.png"))); // NOI18N
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });

        botonLimpiarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicaciondesguace/images/limpiar.png"))); // NOI18N
        botonLimpiarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonNuevoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonChat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonChat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        panelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // funcion que nos lleva al panel anterior
    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed

        // si hay panel anterior
        if(panelActual>1){
            // decremento el contador
            panelActual--;
            // paso al panel anterior
            ((CardLayout)panelPrincipal.getLayout()).previous(panelPrincipal);
            // se puede ir hacia delante
            botonSiguiente.setEnabled(true);
        }
        // si estoy en el primer panel
        if(panelActual==1){
            // deshabilito el boton anterior
            botonAnterior.setEnabled(false);
        }
        
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed

        // si no estoy en el ultimo panel
        if(panelActual < numPaneles){
            // incremento el contador
            panelActual++;
            // paso al siguiente panel
            ((CardLayout)panelPrincipal.getLayout()).next(panelPrincipal);
            // se puede ir al panel anterior
            botonAnterior.setEnabled(true);
        }
        // si estoy en el ultimo panel
        if(panelActual == numPaneles){
            // deshabilito el boton siguiente
            botonSiguiente.setEnabled(false);
        }
        
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSolicitudesActionPerformed

        JPanel p = new PanelSolicitudes(this);
        addPanel(p);

    }//GEN-LAST:event_botonSolicitudesActionPerformed

    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed

        for(int i = 0; i<paneles.size();i++){
            if(paneles.get(i)instanceof PanelSolicitudes){
                ((PanelSolicitudes)paneles.get(i)).Refrescar();
            }
        }

    }//GEN-LAST:event_botonRefrescarActionPerformed

    private void botonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarUsuarioActionPerformed

        JPanel p = new PanelEditarEmpleado(this,empleado);
        addPanel(p);
        
    }//GEN-LAST:event_botonEditarUsuarioActionPerformed

    private void botonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerUsuariosActionPerformed
        JPanel p = new PanelEmpleados(this,empleado);
        addPanel(p);
        
    }//GEN-LAST:event_botonVerUsuariosActionPerformed

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        JPanel p = new PanelNuevoEmpleado(this,empleado);
        addPanel(p);
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonNuevoAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoAdministradorActionPerformed
        JPanel p = new PanelNuevoAdministrador(this,empleado);
        addPanel(p);
    }//GEN-LAST:event_botonNuevoAdministradorActionPerformed

    private void botonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionActionPerformed

        JPanel p = new PanelConfiguracion(this);
        addPanel(p);
    }//GEN-LAST:event_botonConfiguracionActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed

        JPanel p = new PanelRegistro();
        addPanel(p);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonLimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarRegistroActionPerformed

        // pido confirmacion
        int opcion = JOptionPane.showConfirmDialog(null,
                        "Realmente desea borrar el registro, perdera todos los datos anteriores.", "Confirmacion",
                        JOptionPane.YES_NO_OPTION);
        // si acepto
        if (opcion == JOptionPane.YES_OPTION) {

            // creo las variables
            FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                // abro el fichero
                fichero = new FileWriter("Registro.log");
                // creo la variable para escribir
                pw = new PrintWriter(fichero);
                // no escribo nada

            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
               try {
               if (null != fichero)
                  fichero.close();
               } catch (Exception e2) {
                  e2.printStackTrace();
               }
            }
        }
    }//GEN-LAST:event_botonLimpiarRegistroActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBase(new Desguace(),new Empleado()).setVisible(true);
            }
        });
    }

    // anyade un panel a la navegacion
    public void addPanel(JPanel p){
        
        // borro todos los paneles que hay despues del actual
        for(int i=panelActual;i<paneles.size();i++){
            panelPrincipal.remove(i);
            paneles.remove(i);
            //System.out.println("borro");
            i--;
        }
        // actualizo el numero de paneles
        numPaneles=panelActual;

        // anyado el nuevo panel como ultimo
        numPaneles++;
        panelActual=numPaneles;
        panelPrincipal.add(p,""+numPaneles);
        ((CardLayout)panelPrincipal.getLayout()).show(panelPrincipal, ""+numPaneles);
        panelPrincipal.updateUI();
        botonAnterior.setEnabled(true);
        botonSiguiente.setEnabled(false);
        paneles.add(p);
    }

    // borra el ultimo panel
    public void deletePanel(){

        // me voy al anterior
        ((CardLayout)panelPrincipal.getLayout()).previous(panelPrincipal);
        // borro el ultimo
        panelPrincipal.remove(numPaneles-1);
        paneles.remove(numPaneles-1);

        // actualizo las variables
        numPaneles--;
        panelActual=numPaneles;

        // actualizo
        panelPrincipal.updateUI();
        // activo o desactivo el boton anterior
        if(numPaneles>1){
            botonAnterior.setEnabled(true);
        }else{
            botonAnterior.setEnabled(false);
        }
        botonSiguiente.setEnabled(false);

    }

    // escribe el mensaje en el fichero de log
    private void addLog(String s){

        // creo las variables
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            // abro el fichero
            // el segundo parametro es para que todo se anyada al final del fichero
            fichero = new FileWriter("Registro.log",true);
            pw = new PrintWriter(fichero);
            // escribo la fecha y hora y el mensaje
            pw.println(ImprimirFecha(new GregorianCalendar()) + " " + s);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
           try {
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }

    // imprime una fecha formateada
    public String ImprimirFecha(GregorianCalendar f) {

        DecimalFormat format = new DecimalFormat("00");

        return format.format(f.get(GregorianCalendar.DAY_OF_MONTH)) + "." +
                format.format(f.get(GregorianCalendar.MONTH)+1) + "." +
                format.format(f.get(GregorianCalendar.YEAR)) + " " +
                format.format(f.get(GregorianCalendar.HOUR_OF_DAY)) + ":" +
                format.format(f.get(GregorianCalendar.MINUTE)) + ":" +
                format.format(f.get(GregorianCalendar.SECOND));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonChat;
    private javax.swing.JButton botonConectar;
    private javax.swing.JButton botonConfiguracion;
    private javax.swing.JButton botonDesconectar;
    private javax.swing.JButton botonEditarUsuario;
    private javax.swing.JButton botonLimpiarRegistro;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonNuevoAdministrador;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonSolicitudes;
    private javax.swing.JButton botonVerUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    private int numPaneles = 0;
    private int panelActual = 0;
    private Configuracion configuracion;
    private ArrayList<JPanel> paneles = null;
    private Desguace desguace=null;
    private Empleado empleado=null;
}
