/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrimeraVezBienvenida.java
 *
 * Created on 23-ene-2011, 17:29:05
 */

package aplicaciondesguace;

/**
 *
 * @author DAMIAN-MACBOOK
 */
public class PanelPrimeraVezServicios extends javax.swing.JPanel {

    /** Creates new form PanelPrimeraVezBienvenida */
    public PanelPrimeraVezServicios(String ActiveMQ,String WebService) {
        initComponents();

        campoActiveMQ.setText(ActiveMQ);
        campoWS.setText(WebService);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal2 = new javax.swing.JPanel();
        etiqTitulo = new javax.swing.JLabel();
        etiq1 = new javax.swing.JLabel();
        etiq3 = new javax.swing.JLabel();
        etiq2 = new javax.swing.JLabel();
        campoActiveMQ = new javax.swing.JTextField();
        etiqActiveMQ = new javax.swing.JLabel();
        etiqWS = new javax.swing.JLabel();
        campoWS = new javax.swing.JTextField();

        etiqTitulo.setFont(new java.awt.Font("Tahoma", 0, 14));
        etiqTitulo.setForeground(new java.awt.Color(0, 102, 204));
        etiqTitulo.setText("Ubicacion del servidor");

        etiq1.setText("Rellene el siguiente formulario con los datos del servidor en el que se ubica el Servicio de");

        etiq3.setText("Pulsa siguiente para continuar");

        etiq2.setText("Gestion de Compra.");

        campoActiveMQ.setText("tcp://localhost:61616");
        campoActiveMQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoActiveMQActionPerformed(evt);
            }
        });

        etiqActiveMQ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqActiveMQ.setText("Servidor ActiveMQ");

        etiqWS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqWS.setText("Servicio Web");

        campoWS.setText("http://localhost:1132/InterfazRemota.asmx");

        javax.swing.GroupLayout PanelPrincipal2Layout = new javax.swing.GroupLayout(PanelPrincipal2);
        PanelPrincipal2.setLayout(PanelPrincipal2Layout);
        PanelPrincipal2Layout.setHorizontalGroup(
            PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiq3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(etiqTitulo)
                    .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etiq2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiq1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                        .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(etiqWS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiqActiveMQ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoActiveMQ, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoWS, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        PanelPrincipal2Layout.setVerticalGroup(
            PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqTitulo)
                .addGap(18, 18, 18)
                .addComponent(etiq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq2)
                .addGap(36, 36, 36)
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqActiveMQ, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoActiveMQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqWS, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoWS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(etiq3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoActiveMQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoActiveMQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoActiveMQActionPerformed

    public String getActiveMQ(){
        return campoActiveMQ.getText();
    }

    public String getWS(){
        return campoWS.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal2;
    private javax.swing.JTextField campoActiveMQ;
    private javax.swing.JTextField campoWS;
    private javax.swing.JLabel etiq1;
    private javax.swing.JLabel etiq2;
    private javax.swing.JLabel etiq3;
    private javax.swing.JLabel etiqActiveMQ;
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JLabel etiqWS;
    // End of variables declaration//GEN-END:variables

}
