/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPropuesta.java
 *
 * Created on 27-ene-2011, 22:13:25
 */
package aplicaciondesguace;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.GregorianCalendar;


/**
 *
 * @author DAMIAN-MACBOOK
 */
public class PanelEditarEmpleado extends javax.swing.JPanel {

    /** Creates new form PanelPropuesta */
    public PanelEditarEmpleado(FormBase b, Empleado e) {
        initComponents();
        base = b;
        empleado = e;

        // si el empleado que ha iniciado sesion es el mismo que se quiere modificar
        if (b.getEmpleado().getId() == e.getId()) {
            // no puede borrarse a si mismo, desactivamos el boton
            botonBorrar.setEnabled(false);
        }
        // si no
        else{
            // si el empleado es administrador
            if(b.getEmpleado().isAdministrador()){
                // puedo modificar
            }
            // si no
            else{
                // desactivo los campos y el boton de guardar
                campoNombre.setEnabled(false);
                campoPassword1.setEnabled(false);
                campoPassword2.setEnabled(false);
                campoCorreo.setEnabled(false);
                campoNIF.setEnabled(false);
                botonGuardar.setEnabled(false);
                opcionSi.setEnabled(false);
                opcionNo.setEnabled(false);
            }
        }
        // relleno los campos
        campoID.setText(e.getId() + "");
        campoID.setEnabled(false);
        campoUsuario.setText(e.getUsuario() + "");
        campoUsuario.setEnabled(false);
        campoNombre.setText(e.getNombre() + "");
        campoNIF.setText(e.getNif() + "");
        campoCorreo.setText(e.getCorreoElectronico() + "");
        campoPassword1.setText("");
        campoPassword1.setText("");
        if (empleado.isAdministrador()) {
            opcionesAdmin.setSelected(opcionSi.getModel(), true);
        } else {
            opcionesAdmin.setSelected(opcionNo.getModel(), true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesAdmin = new javax.swing.ButtonGroup();
        etiqTitulo = new javax.swing.JLabel();
        etiqID = new javax.swing.JLabel();
        etiqUsuario = new javax.swing.JLabel();
        etiqPassword1 = new javax.swing.JLabel();
        etiqPassword2 = new javax.swing.JLabel();
        etiqNombre = new javax.swing.JLabel();
        etiqNIF = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        campoUsuario = new javax.swing.JTextField();
        campoID = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoNIF = new javax.swing.JTextField();
        etiqLabel = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        etiqAdmin = new javax.swing.JLabel();
        opcionSi = new javax.swing.JRadioButton();
        opcionNo = new javax.swing.JRadioButton();
        botonBorrar = new javax.swing.JButton();
        campoPassword1 = new javax.swing.JPasswordField();
        campoPassword2 = new javax.swing.JPasswordField();

        etiqTitulo.setFont(new java.awt.Font("Tahoma", 1, 18));
        etiqTitulo.setText("Editar Empleado");

        etiqID.setText("ID");

        etiqUsuario.setText("Nombre de usuario");

        etiqPassword1.setText("Contraseña");

        etiqPassword2.setText("Contraseña(otra vez)");

        etiqNombre.setText("Nombre completo");

        etiqNIF.setText("NIF");

        botonGuardar.setFont(new java.awt.Font("Tahoma", 1, 11));
        botonGuardar.setText("Guardar usuario");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNIFActionPerformed(evt);
            }
        });

        etiqLabel.setText("Correo electrónico");

        campoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoActionPerformed(evt);
            }
        });

        etiqAdmin.setText("Adminstrador");

        opcionesAdmin.add(opcionSi);
        opcionSi.setText("Si");
        opcionSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSiActionPerformed(evt);
            }
        });

        opcionesAdmin.add(opcionNo);
        opcionNo.setText("No");

        botonBorrar.setText("Borrar usuario");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiqPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiqUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiqID, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                    .addComponent(campoID, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                    .addComponent(campoNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opcionSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(opcionNo))
                                    .addComponent(campoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqPassword2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(667, 667, 667))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(667, 667, 667))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(667, 667, 667))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(667, 667, 667))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqID)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqUsuario)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqPassword2)
                    .addComponent(campoPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqNIF)
                    .addComponent(campoNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqLabel)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqAdmin)
                    .addComponent(opcionSi)
                    .addComponent(opcionNo))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonBorrar))
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNIFActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    private void opcionSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionSiActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        // guardo los valores introducidos en los campos
        empleado.setAdministrador(opcionSi.isSelected());
        empleado.setCorreoElectronico(campoCorreo.getText());
        empleado.setNif(campoNIF.getText());
        empleado.setNombre(campoNombre.getText());
        // guardo los datos
        empleado.guardarDatosEmpleado(base.getConfiguracion().getBdHost());
        // borro el panel
        base.deletePanel();
        // dejo constancia en el log
        addLog("Editado un empleado: " + empleado.getId() + "(" + empleado.getUsuario() + ")");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed

        // borro el empleado
        empleado.borrar(base.getConfiguracion().getBdHost());
        // borro el panel
        base.deletePanel();
        // dejo constancia en el log
        addLog("borrado un empleado: " + empleado.getId() + "(" + empleado.getUsuario() + ")");

    }//GEN-LAST:event_botonBorrarActionPerformed

    private void addLog(String s){
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro.log",true);
            pw = new PrintWriter(fichero);

            pw.println(ImprimirFecha(new GregorianCalendar()) + " " + s);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
           try {
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }
    public String ImprimirFecha(GregorianCalendar f) {

        DecimalFormat format = new DecimalFormat("00");

        return format.format(f.get(GregorianCalendar.DAY_OF_MONTH)) + "." +
                format.format(f.get(GregorianCalendar.MONTH)+1) + "." +
                format.format(f.get(GregorianCalendar.YEAR)) + " " +
                format.format(f.get(GregorianCalendar.HOUR_OF_DAY)) + ":" +
                format.format(f.get(GregorianCalendar.MINUTE)) + ":" +
                format.format(f.get(GregorianCalendar.SECOND));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNIF;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPasswordField campoPassword1;
    private javax.swing.JPasswordField campoPassword2;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiqAdmin;
    private javax.swing.JLabel etiqID;
    private javax.swing.JLabel etiqLabel;
    private javax.swing.JLabel etiqNIF;
    private javax.swing.JLabel etiqNombre;
    private javax.swing.JLabel etiqPassword1;
    private javax.swing.JLabel etiqPassword2;
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JLabel etiqUsuario;
    private javax.swing.JRadioButton opcionNo;
    private javax.swing.JRadioButton opcionSi;
    private javax.swing.ButtonGroup opcionesAdmin;
    // End of variables declaration//GEN-END:variables
    private FormBase base;
    private Empleado empleado;
}
