/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPropuestas.java
 *
 * Created on 27-ene-2011, 22:34:09
 */
package aplicaciondesguace;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.Timer;

/**
 *
 * @author DAMIAN-MACBOOK
 */
public class PanelRegistro extends javax.swing.JPanel {

    /** Creates new form PanelPropuestas */
    public PanelRegistro() {
        initComponents();

        // creo un timer que refresque cada 10 segundos
        Timer timer = new Timer(10000, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                refrescar();
            }
        });

        // comienza el timer
        timer.start();

        // refresco al comienzo
        refrescar();
    }

    // actualiza el contenido del registro
    public void refrescar() {

        // limpio el texto del registro
        textoRegistro.setText("");
        // creo las variables
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {
            // abro el fichero
            archivo = new File("Registro.log");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);

            // copio el contenido linea a linea a partir del fichero
            String linea;
            while ((linea = br.readLine()) != null) {
                textoRegistro.setText(textoRegistro.getText() + linea + "\n");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // En el finally cerramos el fichero, para asegurarnos
            // que se cierra tanto si todo va bien como si salta
            // una excepcion.
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoRegistro = new javax.swing.JTextArea();

        etiqTitulo.setFont(new java.awt.Font("Tahoma", 1, 18));
        etiqTitulo.setText("Registro ");

        textoRegistro.setColumns(20);
        textoRegistro.setRows(5);
        jScrollPane1.setViewportView(textoRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                    .addComponent(etiqTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoRegistro;
    // End of variables declaration//GEN-END:variables
}
