//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Sitio_Web.SGC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InterfazRemotaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class InterfazRemota : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InicializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarPiezaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProponerPiezaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClientePorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDesguaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDesguacePorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDesguaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroDesguaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPropuestasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFinalizadasNoSincronizadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSolicitudesPorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSolicitudPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPropuestaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPropuestasConfirmadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarPropuestaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InterfazRemota() {
            this.Url = global::Sitio_Web.Properties.Settings.Default.Sitio_Web_criludage_interfaz_InterfazRemota;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InicializarCompletedEventHandler InicializarCompleted;
        
        /// <remarks/>
        public event SolicitarPiezaCompletedEventHandler SolicitarPiezaCompleted;
        
        /// <remarks/>
        public event ProponerPiezaCompletedEventHandler ProponerPiezaCompleted;
        
        /// <remarks/>
        public event ObtenerClienteCompletedEventHandler ObtenerClienteCompleted;
        
        /// <remarks/>
        public event ObtenerClientePorUsuarioCompletedEventHandler ObtenerClientePorUsuarioCompleted;
        
        /// <remarks/>
        public event ObtenerDesguaceCompletedEventHandler ObtenerDesguaceCompleted;
        
        /// <remarks/>
        public event ObtenerDesguacePorUsuarioCompletedEventHandler ObtenerDesguacePorUsuarioCompleted;
        
        /// <remarks/>
        public event ActualizarClienteCompletedEventHandler ActualizarClienteCompleted;
        
        /// <remarks/>
        public event ActualizarDesguaceCompletedEventHandler ActualizarDesguaceCompleted;
        
        /// <remarks/>
        public event RegistroClienteCompletedEventHandler RegistroClienteCompleted;
        
        /// <remarks/>
        public event RegistroDesguaceCompletedEventHandler RegistroDesguaceCompleted;
        
        /// <remarks/>
        public event ObtenerPropuestasCompletedEventHandler ObtenerPropuestasCompleted;
        
        /// <remarks/>
        public event ObtenerFinalizadasNoSincronizadasCompletedEventHandler ObtenerFinalizadasNoSincronizadasCompleted;
        
        /// <remarks/>
        public event ObtenerSolicitudesPorUsuarioCompletedEventHandler ObtenerSolicitudesPorUsuarioCompleted;
        
        /// <remarks/>
        public event ObtenerSolicitudPorIdCompletedEventHandler ObtenerSolicitudPorIdCompleted;
        
        /// <remarks/>
        public event ObtenerPropuestaPorIdCompletedEventHandler ObtenerPropuestaPorIdCompleted;
        
        /// <remarks/>
        public event ObtenerPropuestasConfirmadasCompletedEventHandler ObtenerPropuestasConfirmadasCompleted;
        
        /// <remarks/>
        public event ConfirmarPropuestaCompletedEventHandler ConfirmarPropuestaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Inicializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Inicializar() {
            this.Invoke("Inicializar", new object[0]);
        }
        
        /// <remarks/>
        public void InicializarAsync() {
            this.InicializarAsync(null);
        }
        
        /// <remarks/>
        public void InicializarAsync(object userState) {
            if ((this.InicializarOperationCompleted == null)) {
                this.InicializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInicializarOperationCompleted);
            }
            this.InvokeAsync("Inicializar", new object[0], this.InicializarOperationCompleted, userState);
        }
        
        private void OnInicializarOperationCompleted(object arg) {
            if ((this.InicializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InicializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitarPieza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SolicitarPieza(ENSolicitud solicitud, string usuario, string contrasena) {
            object[] results = this.Invoke("SolicitarPieza", new object[] {
                        solicitud,
                        usuario,
                        contrasena});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarPiezaAsync(ENSolicitud solicitud, string usuario, string contrasena) {
            this.SolicitarPiezaAsync(solicitud, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void SolicitarPiezaAsync(ENSolicitud solicitud, string usuario, string contrasena, object userState) {
            if ((this.SolicitarPiezaOperationCompleted == null)) {
                this.SolicitarPiezaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarPiezaOperationCompleted);
            }
            this.InvokeAsync("SolicitarPieza", new object[] {
                        solicitud,
                        usuario,
                        contrasena}, this.SolicitarPiezaOperationCompleted, userState);
        }
        
        private void OnSolicitarPiezaOperationCompleted(object arg) {
            if ((this.SolicitarPiezaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarPiezaCompleted(this, new SolicitarPiezaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProponerPieza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProponerPieza(ENPropuesta propuesta, string usuario, string contrasena) {
            object[] results = this.Invoke("ProponerPieza", new object[] {
                        propuesta,
                        usuario,
                        contrasena});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProponerPiezaAsync(ENPropuesta propuesta, string usuario, string contrasena) {
            this.ProponerPiezaAsync(propuesta, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ProponerPiezaAsync(ENPropuesta propuesta, string usuario, string contrasena, object userState) {
            if ((this.ProponerPiezaOperationCompleted == null)) {
                this.ProponerPiezaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProponerPiezaOperationCompleted);
            }
            this.InvokeAsync("ProponerPieza", new object[] {
                        propuesta,
                        usuario,
                        contrasena}, this.ProponerPiezaOperationCompleted, userState);
        }
        
        private void OnProponerPiezaOperationCompleted(object arg) {
            if ((this.ProponerPiezaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProponerPiezaCompleted(this, new ProponerPiezaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENCliente ObtenerCliente(int id, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerCliente", new object[] {
                        id,
                        usuario,
                        contrasena});
            return ((ENCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(int id, string usuario, string contrasena) {
            this.ObtenerClienteAsync(id, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(int id, string usuario, string contrasena, object userState) {
            if ((this.ObtenerClienteOperationCompleted == null)) {
                this.ObtenerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerCliente", new object[] {
                        id,
                        usuario,
                        contrasena}, this.ObtenerClienteOperationCompleted, userState);
        }
        
        private void OnObtenerClienteOperationCompleted(object arg) {
            if ((this.ObtenerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClienteCompleted(this, new ObtenerClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerClientePorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENCliente ObtenerClientePorUsuario(string cliente, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerClientePorUsuario", new object[] {
                        cliente,
                        usuario,
                        contrasena});
            return ((ENCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClientePorUsuarioAsync(string cliente, string usuario, string contrasena) {
            this.ObtenerClientePorUsuarioAsync(cliente, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerClientePorUsuarioAsync(string cliente, string usuario, string contrasena, object userState) {
            if ((this.ObtenerClientePorUsuarioOperationCompleted == null)) {
                this.ObtenerClientePorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClientePorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerClientePorUsuario", new object[] {
                        cliente,
                        usuario,
                        contrasena}, this.ObtenerClientePorUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerClientePorUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerClientePorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClientePorUsuarioCompleted(this, new ObtenerClientePorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDesguace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENDesguace ObtenerDesguace(int id, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerDesguace", new object[] {
                        id,
                        usuario,
                        contrasena});
            return ((ENDesguace)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDesguaceAsync(int id, string usuario, string contrasena) {
            this.ObtenerDesguaceAsync(id, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerDesguaceAsync(int id, string usuario, string contrasena, object userState) {
            if ((this.ObtenerDesguaceOperationCompleted == null)) {
                this.ObtenerDesguaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDesguaceOperationCompleted);
            }
            this.InvokeAsync("ObtenerDesguace", new object[] {
                        id,
                        usuario,
                        contrasena}, this.ObtenerDesguaceOperationCompleted, userState);
        }
        
        private void OnObtenerDesguaceOperationCompleted(object arg) {
            if ((this.ObtenerDesguaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDesguaceCompleted(this, new ObtenerDesguaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDesguacePorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENDesguace ObtenerDesguacePorUsuario(string desguace, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerDesguacePorUsuario", new object[] {
                        desguace,
                        usuario,
                        contrasena});
            return ((ENDesguace)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDesguacePorUsuarioAsync(string desguace, string usuario, string contrasena) {
            this.ObtenerDesguacePorUsuarioAsync(desguace, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerDesguacePorUsuarioAsync(string desguace, string usuario, string contrasena, object userState) {
            if ((this.ObtenerDesguacePorUsuarioOperationCompleted == null)) {
                this.ObtenerDesguacePorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDesguacePorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerDesguacePorUsuario", new object[] {
                        desguace,
                        usuario,
                        contrasena}, this.ObtenerDesguacePorUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerDesguacePorUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerDesguacePorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDesguacePorUsuarioCompleted(this, new ObtenerDesguacePorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarCliente(ENCliente cliente, string usuario, string contrasena) {
            object[] results = this.Invoke("ActualizarCliente", new object[] {
                        cliente,
                        usuario,
                        contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(ENCliente cliente, string usuario, string contrasena) {
            this.ActualizarClienteAsync(cliente, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(ENCliente cliente, string usuario, string contrasena, object userState) {
            if ((this.ActualizarClienteOperationCompleted == null)) {
                this.ActualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarClienteOperationCompleted);
            }
            this.InvokeAsync("ActualizarCliente", new object[] {
                        cliente,
                        usuario,
                        contrasena}, this.ActualizarClienteOperationCompleted, userState);
        }
        
        private void OnActualizarClienteOperationCompleted(object arg) {
            if ((this.ActualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarClienteCompleted(this, new ActualizarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDesguace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarDesguace(ENDesguace desguace, string usuario, string contrasena) {
            object[] results = this.Invoke("ActualizarDesguace", new object[] {
                        desguace,
                        usuario,
                        contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarDesguaceAsync(ENDesguace desguace, string usuario, string contrasena) {
            this.ActualizarDesguaceAsync(desguace, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ActualizarDesguaceAsync(ENDesguace desguace, string usuario, string contrasena, object userState) {
            if ((this.ActualizarDesguaceOperationCompleted == null)) {
                this.ActualizarDesguaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDesguaceOperationCompleted);
            }
            this.InvokeAsync("ActualizarDesguace", new object[] {
                        desguace,
                        usuario,
                        contrasena}, this.ActualizarDesguaceOperationCompleted, userState);
        }
        
        private void OnActualizarDesguaceOperationCompleted(object arg) {
            if ((this.ActualizarDesguaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDesguaceCompleted(this, new ActualizarDesguaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegistroCliente(ENCliente cliente) {
            object[] results = this.Invoke("RegistroCliente", new object[] {
                        cliente});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroClienteAsync(ENCliente cliente) {
            this.RegistroClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void RegistroClienteAsync(ENCliente cliente, object userState) {
            if ((this.RegistroClienteOperationCompleted == null)) {
                this.RegistroClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroClienteOperationCompleted);
            }
            this.InvokeAsync("RegistroCliente", new object[] {
                        cliente}, this.RegistroClienteOperationCompleted, userState);
        }
        
        private void OnRegistroClienteOperationCompleted(object arg) {
            if ((this.RegistroClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroClienteCompleted(this, new RegistroClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroDesguace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegistroDesguace(ENDesguace desguace) {
            object[] results = this.Invoke("RegistroDesguace", new object[] {
                        desguace});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroDesguaceAsync(ENDesguace desguace) {
            this.RegistroDesguaceAsync(desguace, null);
        }
        
        /// <remarks/>
        public void RegistroDesguaceAsync(ENDesguace desguace, object userState) {
            if ((this.RegistroDesguaceOperationCompleted == null)) {
                this.RegistroDesguaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroDesguaceOperationCompleted);
            }
            this.InvokeAsync("RegistroDesguace", new object[] {
                        desguace}, this.RegistroDesguaceOperationCompleted, userState);
        }
        
        private void OnRegistroDesguaceOperationCompleted(object arg) {
            if ((this.RegistroDesguaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroDesguaceCompleted(this, new RegistroDesguaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPropuestas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ObtenerPropuestas(ENSolicitud solicitud, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerPropuestas", new object[] {
                        solicitud,
                        usuario,
                        contrasena});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPropuestasAsync(ENSolicitud solicitud, string usuario, string contrasena) {
            this.ObtenerPropuestasAsync(solicitud, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerPropuestasAsync(ENSolicitud solicitud, string usuario, string contrasena, object userState) {
            if ((this.ObtenerPropuestasOperationCompleted == null)) {
                this.ObtenerPropuestasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPropuestasOperationCompleted);
            }
            this.InvokeAsync("ObtenerPropuestas", new object[] {
                        solicitud,
                        usuario,
                        contrasena}, this.ObtenerPropuestasOperationCompleted, userState);
        }
        
        private void OnObtenerPropuestasOperationCompleted(object arg) {
            if ((this.ObtenerPropuestasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPropuestasCompleted(this, new ObtenerPropuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerFinalizadasNoSincronizadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ObtenerFinalizadasNoSincronizadas(string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerFinalizadasNoSincronizadas", new object[] {
                        usuario,
                        contrasena});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFinalizadasNoSincronizadasAsync(string usuario, string contrasena) {
            this.ObtenerFinalizadasNoSincronizadasAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerFinalizadasNoSincronizadasAsync(string usuario, string contrasena, object userState) {
            if ((this.ObtenerFinalizadasNoSincronizadasOperationCompleted == null)) {
                this.ObtenerFinalizadasNoSincronizadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFinalizadasNoSincronizadasOperationCompleted);
            }
            this.InvokeAsync("ObtenerFinalizadasNoSincronizadas", new object[] {
                        usuario,
                        contrasena}, this.ObtenerFinalizadasNoSincronizadasOperationCompleted, userState);
        }
        
        private void OnObtenerFinalizadasNoSincronizadasOperationCompleted(object arg) {
            if ((this.ObtenerFinalizadasNoSincronizadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFinalizadasNoSincronizadasCompleted(this, new ObtenerFinalizadasNoSincronizadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSolicitudesPorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ObtenerSolicitudesPorUsuario(string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerSolicitudesPorUsuario", new object[] {
                        usuario,
                        contrasena});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSolicitudesPorUsuarioAsync(string usuario, string contrasena) {
            this.ObtenerSolicitudesPorUsuarioAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerSolicitudesPorUsuarioAsync(string usuario, string contrasena, object userState) {
            if ((this.ObtenerSolicitudesPorUsuarioOperationCompleted == null)) {
                this.ObtenerSolicitudesPorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSolicitudesPorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerSolicitudesPorUsuario", new object[] {
                        usuario,
                        contrasena}, this.ObtenerSolicitudesPorUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerSolicitudesPorUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerSolicitudesPorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSolicitudesPorUsuarioCompleted(this, new ObtenerSolicitudesPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSolicitudPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENSolicitud ObtenerSolicitudPorId(int id, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerSolicitudPorId", new object[] {
                        id,
                        usuario,
                        contrasena});
            return ((ENSolicitud)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSolicitudPorIdAsync(int id, string usuario, string contrasena) {
            this.ObtenerSolicitudPorIdAsync(id, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerSolicitudPorIdAsync(int id, string usuario, string contrasena, object userState) {
            if ((this.ObtenerSolicitudPorIdOperationCompleted == null)) {
                this.ObtenerSolicitudPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSolicitudPorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerSolicitudPorId", new object[] {
                        id,
                        usuario,
                        contrasena}, this.ObtenerSolicitudPorIdOperationCompleted, userState);
        }
        
        private void OnObtenerSolicitudPorIdOperationCompleted(object arg) {
            if ((this.ObtenerSolicitudPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSolicitudPorIdCompleted(this, new ObtenerSolicitudPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPropuestaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ENPropuesta ObtenerPropuestaPorId(int id, string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerPropuestaPorId", new object[] {
                        id,
                        usuario,
                        contrasena});
            return ((ENPropuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPropuestaPorIdAsync(int id, string usuario, string contrasena) {
            this.ObtenerPropuestaPorIdAsync(id, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerPropuestaPorIdAsync(int id, string usuario, string contrasena, object userState) {
            if ((this.ObtenerPropuestaPorIdOperationCompleted == null)) {
                this.ObtenerPropuestaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPropuestaPorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerPropuestaPorId", new object[] {
                        id,
                        usuario,
                        contrasena}, this.ObtenerPropuestaPorIdOperationCompleted, userState);
        }
        
        private void OnObtenerPropuestaPorIdOperationCompleted(object arg) {
            if ((this.ObtenerPropuestaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPropuestaPorIdCompleted(this, new ObtenerPropuestaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPropuestasConfirmadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ObtenerPropuestasConfirmadas(string usuario, string contrasena) {
            object[] results = this.Invoke("ObtenerPropuestasConfirmadas", new object[] {
                        usuario,
                        contrasena});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPropuestasConfirmadasAsync(string usuario, string contrasena) {
            this.ObtenerPropuestasConfirmadasAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ObtenerPropuestasConfirmadasAsync(string usuario, string contrasena, object userState) {
            if ((this.ObtenerPropuestasConfirmadasOperationCompleted == null)) {
                this.ObtenerPropuestasConfirmadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPropuestasConfirmadasOperationCompleted);
            }
            this.InvokeAsync("ObtenerPropuestasConfirmadas", new object[] {
                        usuario,
                        contrasena}, this.ObtenerPropuestasConfirmadasOperationCompleted, userState);
        }
        
        private void OnObtenerPropuestasConfirmadasOperationCompleted(object arg) {
            if ((this.ObtenerPropuestasConfirmadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPropuestasConfirmadasCompleted(this, new ObtenerPropuestasConfirmadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarPropuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ConfirmarPropuesta(ENPropuesta propuesta, string usuario, string contrasena) {
            object[] results = this.Invoke("ConfirmarPropuesta", new object[] {
                        propuesta,
                        usuario,
                        contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarPropuestaAsync(ENPropuesta propuesta, string usuario, string contrasena) {
            this.ConfirmarPropuestaAsync(propuesta, usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ConfirmarPropuestaAsync(ENPropuesta propuesta, string usuario, string contrasena, object userState) {
            if ((this.ConfirmarPropuestaOperationCompleted == null)) {
                this.ConfirmarPropuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarPropuestaOperationCompleted);
            }
            this.InvokeAsync("ConfirmarPropuesta", new object[] {
                        propuesta,
                        usuario,
                        contrasena}, this.ConfirmarPropuestaOperationCompleted, userState);
        }
        
        private void OnConfirmarPropuestaOperationCompleted(object arg) {
            if ((this.ConfirmarPropuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarPropuestaCompleted(this, new ConfirmarPropuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENSolicitud {
        
        private int idField;
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private bool negociadoAutomaticoField;
        
        private System.DateTime fechaRespuestaField;
        
        private System.DateTime fechaEntregaField;
        
        private ENEstadosPieza estadoField;
        
        private float precioMaxField;
        
        private int idClienteField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public bool NegociadoAutomatico {
            get {
                return this.negociadoAutomaticoField;
            }
            set {
                this.negociadoAutomaticoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
            }
        }
        
        /// <comentarios/>
        public ENEstadosPieza Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public float PrecioMax {
            get {
                return this.precioMaxField;
            }
            set {
                this.precioMaxField = value;
            }
        }
        
        /// <comentarios/>
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ENEstadosPieza {
        
        /// <comentarios/>
        USADA,
        
        /// <comentarios/>
        NUEVA,
        
        /// <comentarios/>
        NO_FUNCIONA,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENDesguace {
        
        private int idField;
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string nombreField;
        
        private string nifField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private string informacionAdicionalField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nif {
            get {
                return this.nifField;
            }
            set {
                this.nifField = value;
            }
        }
        
        /// <comentarios/>
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENCliente {
        
        private int idField;
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string nombreField;
        
        private string nifField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private string informacionAdicionalField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nif {
            get {
                return this.nifField;
            }
            set {
                this.nifField = value;
            }
        }
        
        /// <comentarios/>
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENPropuesta {
        
        private int idField;
        
        private string descripcionField;
        
        private System.DateTime fechaEntregaField;
        
        private ENEstadosPieza estadoField;
        
        private float precioField;
        
        private byte[] fotoField;
        
        private bool confirmadaField;
        
        private int idDesguaceField;
        
        private int idSolicitudField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
            }
        }
        
        /// <comentarios/>
        public ENEstadosPieza Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public float Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <comentarios/>
        public bool Confirmada {
            get {
                return this.confirmadaField;
            }
            set {
                this.confirmadaField = value;
            }
        }
        
        /// <comentarios/>
        public int IdDesguace {
            get {
                return this.idDesguaceField;
            }
            set {
                this.idDesguaceField = value;
            }
        }
        
        /// <comentarios/>
        public int IdSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                this.idSolicitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InicializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SolicitarPiezaCompletedEventHandler(object sender, SolicitarPiezaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarPiezaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarPiezaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProponerPiezaCompletedEventHandler(object sender, ProponerPiezaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProponerPiezaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProponerPiezaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerClienteCompletedEventHandler(object sender, ObtenerClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerClientePorUsuarioCompletedEventHandler(object sender, ObtenerClientePorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClientePorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClientePorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerDesguaceCompletedEventHandler(object sender, ObtenerDesguaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDesguaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDesguaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENDesguace Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENDesguace)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerDesguacePorUsuarioCompletedEventHandler(object sender, ObtenerDesguacePorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDesguacePorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDesguacePorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENDesguace Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENDesguace)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizarClienteCompletedEventHandler(object sender, ActualizarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizarDesguaceCompletedEventHandler(object sender, ActualizarDesguaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDesguaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDesguaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroClienteCompletedEventHandler(object sender, RegistroClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroDesguaceCompletedEventHandler(object sender, RegistroDesguaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroDesguaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroDesguaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPropuestasCompletedEventHandler(object sender, ObtenerPropuestasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPropuestasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPropuestasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerFinalizadasNoSincronizadasCompletedEventHandler(object sender, ObtenerFinalizadasNoSincronizadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFinalizadasNoSincronizadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFinalizadasNoSincronizadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerSolicitudesPorUsuarioCompletedEventHandler(object sender, ObtenerSolicitudesPorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSolicitudesPorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSolicitudesPorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerSolicitudPorIdCompletedEventHandler(object sender, ObtenerSolicitudPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSolicitudPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSolicitudPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENSolicitud Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENSolicitud)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPropuestaPorIdCompletedEventHandler(object sender, ObtenerPropuestaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPropuestaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPropuestaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ENPropuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ENPropuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPropuestasConfirmadasCompletedEventHandler(object sender, ObtenerPropuestasConfirmadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPropuestasConfirmadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPropuestasConfirmadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmarPropuestaCompletedEventHandler(object sender, ConfirmarPropuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarPropuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarPropuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591